/* Cursores, CURSORES E PROCEDURES */

CREATE TABLE LIVROS(
	IDLIVRO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100),
	VALOR DECIMAL(10,2))

INSERT INTO LIVROS VALUES('SQL',100.00)
INSERT INTO LIVROS VALUES('JAVA',60.00)
INSERT INTO LIVROS VALUES('PYTHON',110.00)
INSERT INTO LIVROS VALUES('SPARK',190.00)

SELECT * FROM LIVROS

/* CRIANDO CURSOR*/

DECLARE 
	C_REG CURSOR FOR 
	SELECT NOME, VALOR FROM LIVROS 
DECLARE
	@NOME VARCHAR(30),
	@VALOR DECIMAL(10,2)

OPEN C_REG

FETCH NEXT FROM C_REG
INTO @NOME,@VALOR

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'VALOR DO LIVRO' +@NOME + ' R$' + CAST(@VALOR AS VARCHAR(10))

	FETCH NEXT FROM C_REG
	INTO @NOME,@VALOR
END
CLOSE C_REG
DEALLOCATE C_REG
GO


SELECT idnota FROM nota_fiscal
WHERE idnota NOT IN (SELECT id_nota_fiscal FROM item_nota)
ORDER BY 1
GO

SELECT * FROM item_nota
GO

/* DECLARE COM CURSOR PARA INSERIR IDS FALTANTES*/

CREATE PROCEDURE  C_CURSOR AS 

DECLARE 
	C_NOTAS CURSOR FOR
	SELECT IDNOTA FROM NOTA_FISCAL 
	WHERE IDNOTA NOT IN(SELECT ID_NOTA_FISCAL FROM item_nota)

DECLARE
	@IDNOTA INT,
	@ID_PRODUTO INT,
	@TOTAL DECIMAL

OPEN C_NOTAS
FETCH NEXT FROM C_NOTAS
INTO @IDNOTA

WHILE @@FETCH_STATUS =0
BEGIN 
	SET @ID_PRODUTO =
		(SELECT TOP 1 IDPRODUTO FROM produto ORDER BY NEWID())
	SET @TOTAL = 
		(SELECT VALOR FROM PRODUTO WHERE IDPRODUTO  = @ID_PRODUTO)
	INSERT INTO item_nota(id_produt, id_nota_fiscal,qtd,total) 
	VALUES(@ID_PRODUTO, @IDNOTA,1,@TOTAL)

FETCH NEXT FROM C_NOTAS
INTO @IDNOTA


END

CLOSE C_NOTAS

DEALLOCATE C_NOTAS
GO

EXECUTE C_CURSOR
GO


